7th-Mile/trip-for-p

src/main/java/team/seventhmile/tripforp/TripForPApplication.java

- close #4 
> 주요 변경 사항 목록
> 기타 사항

docs: PR 템플릿 변경

---

src/main/java/team/seventhmile/tripforp/TripForPApplication.java

- close #6 
> 주요 변경 사항 목록
> 기타 사항

feat: test

---

src/main/java/team/seventhmile/tripforp/domain/plan/entity/PlanItem.java

-planitementity기능구현
- close #12 
-planitementity기능구현
-없음

[#12] :sparkles: feat: <PlanItemEntity기능구현>

---

src/main/java/team/seventhmile/tripforp/magazine/entity.java

- close 
> 매거진 엔티티 작성
> 회원 id 아직 미작성

[#14] ✨feat: 매거진 엔티티 작성

---

src/main/java/team/seventhmile/tripforp/domain/plan/entity/Area.java
src/main/java/team/seventhmile/tripforp/domain/plan/entity/Plan.java

> 여행 코스 엔티티 개발
- close #11 
- 엔티티 작성
- 지역 Enum 작성
- 회원 ID 작성 필요
- 여행 상세 계획 작성 필요

[#11] :sparkles: feat: 여행 코스 엔티티 개발

---

src/main/java/team/seventhmile/tripforp/domain/plan/entity/Place.java

- Place entity 기능구현
- close #26 
- Place entity 기능구현
-

[#26] :sparkles: feat: <Place entity기능구현>

---

src/main/java/team/seventhmile/tripforp/domain/review/entity/ReviewPost.java

- ReviewPost Entity 개발
- close #27

[#27] ✨feat: ReviewPost Entity 개발

---

src/main/java/team/seventhmile/tripforp/domain/free_post/entity/FreePost.java

- FreePost Entity 개발
- close #19

[#19] ✨feat: FreePost Entity 개발

---

src/main/java/team/seventhmile/tripforp/magazine/entity.java

> 매거진 엔티티 수정
- close #31 
- 클래스명 entity -> Entity로 수정
- Table 이름을 magazine -> magazines로 수정
- 수정 로직 추가
- Not Null 예외 처리 로직 추가
- 게시글 삭제일 삭제
> 기타 사항

[#31] ✨feat: 매거진 엔티티 수정

---

src/main/java/team/seventhmile/tripforp/domain/review_post/entity/ReviewPost.java

🐛fix: ReviewPost 패키지 명 변경에 따른 경로 수정
- close #33

[#33] 🐛fix: ReviewPost 패키지 명 변경에 따른 경로 수정

---

src/main/java/team/seventhmile/tripforp/magazine/Dto.java

> 매거진 DTO 생성
- close #36 
- 제목, 내용에 대한 글자수 제한
- dto -> entity 변환 로직
- entity -> dto 변환 로직
> 기타 사항

[#36] ✨feat: 매거진 DTO 생성

---

src/main/java/team/seventhmile/tripforp/domain/user/entity/Role.java
src/main/java/team/seventhmile/tripforp/domain/user/entity/User.java

> User entity 개발
- close #30 
> User의 Entity와 Role Enum 구현
> 추후 리팩토링 예정입니다.

[#30]✨ feat: User Entity 개발

---

src/main/java/team/seventhmile/tripforp/magazine/Repository.java

> 매거진 레포지토리 생성
- close #41 
- 게시글 id 내림차순으로 불러오기 (findAllByOrderByIdDesc 메소드)
- 게시글 id로 찾기 (findById 메소드)
> 기타 사항

[#41] ✨feat: 매거진 레포지토리 생성

---

src/main/java/team/seventhmile/tripforp/domain/magazine/service/MagazineService.java

> 매거진 서비스 생성
- close #44 
- 매거진 글 목록 조회
- 글 상세 보기
- 글 작성하기
- 글 수정하기
- 글 삭제하기 (하드 딜리트)
- 글 작성, 수정, 삭제 메소드에 권한(ADMIN) 확인 메소드 아직 미기재

[#44] ✨feat: 매거진 서비스 생성

---

src/main/java/team/seventhmile/tripforp/domain/plan/entity/PlanLike.java
src/main/java/team/seventhmile/tripforp/domain/plan/repository/PlanLikeRepository.java

> 여행 코스 좋아요 레포지토리 생성
- close #46 
> User, Plan 관련 주석 해제
> 여행 코스 좋아요 레포지토리 생성
> 기타 사항

[#46] ✨feat: 여행 코스 좋아요 레포지토리 생성

---

src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanLikeService.java

> 여행 코스 좋아요 서비스 생성
- close #48 
> 여행 코스 좋아요, 좋아요 취소 로직 추가
> 기타 사항

[#48] ✨ feat: 여행 코스 좋아요 서비스 생성

---

src/main/java/team/seventhmile/tripforp/domain/plan/dto/PlanLikeDto.java

> 여행 코스 좋아요 DTO 생성
- close #50 
>여행 코스 좋아요 DTO 생성
> 기타 사항

[#50] ✨ feat: 여행 코스 좋아요 DTO 생성

---

src/main/java/team/seventhmile/tripforp/domain/plan/controller/PlanLikeController.java

> 여행코스 좋아요, 취소 요청 처리
- close  #56 
> 주요 변경 사항 목록
> 이전에 작성해둔 주석처리된 부분 활성화 및 User, Plan import

[#56] ✨ feat: 여행 코스 좋아요, 취소 요청 처리

---

src/main/java/team/seventhmile/tripforp/domain/magazine/controller/MagazineController.java

> 매거진 컨트롤러 생성
- close #61 
> 기본적인 CRUD 구현
> 기타 사항

[#61] ✨feat: 매거진 컨트롤러 생성

---

frontend/.gitignore
frontend/package.json
frontend/src/api/index.js
frontend/src/router/index.js
frontend/src/views/ChatView.vue
frontend/src/views/MapView.vue
frontend/src/views/SearchPlaceView.vue
frontend/vue.config.js
src/main/java/team/seventhmile/tripforp/external/alan/controller/AlanApiController.java
src/main/java/team/seventhmile/tripforp/external/alan/dto/AlanApiResponse.java
src/main/java/team/seventhmile/tripforp/external/alan/service/AlanApiService.java
src/main/java/team/seventhmile/tripforp/global/config/RestTemplateConfig.java

>앨런 API 1차 구현 및 카카오 지도 API 장소 검색 구현
- close #60 
> 주요 변경 사항 목록
> 기타 사항

[#60] ✨ feat: 앨런 API 1차 구현 및 카카오 지도 API 장소 검색 구현

---

src/main/java/team/seventhmile/tripforp/domain/plan/controller/PlanGetController.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/PlanGetDto.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/PlanListItemDto.java
src/main/java/team/seventhmile/tripforp/domain/plan/entity/Plan.java
src/main/java/team/seventhmile/tripforp/domain/plan/entity/PlanItem.java
src/main/java/team/seventhmile/tripforp/domain/plan/repository/PlanGetRepository.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanGetService.java
src/test/java/team/seventhmile/tripforp/domain/plan/controller/PlanGetControllerTest.java
src/test/java/team/seventhmile/tripforp/domain/plan/repository/PlanGetRepositoryTest.java
src/test/java/team/seventhmile/tripforp/domain/plan/service/PlanGetServiceTest.java

- 여행코스목록조회기능구현
- close #55 
- 여행코스목록조회기능구현

[#55] :sparkles: feat: <여행코스목록조회기능구현>

---

src/main/java/team/seventhmile/tripforp/domain/free_comment/FreeComment.java

> 자유게시판 댓글 엔티티 생성
- close #64 
- 댓글 id (pk)
- 자유 게시글 id (fk)
- 회원 id (fk)
- 내용
- 댓글 생성일
- 댓글 수정일
> 기타 사항

[#64] ✨feat: 자유게시판 댓글 엔티티 생성

---

src/main/java/team/seventhmile/tripforp/domain/free_comment/FreeComment.java
src/main/java/team/seventhmile/tripforp/domain/free_comment/FreeCommentDto.java

> 자유게시판 댓글 DTO 생성
- close #66 
> 자유게시판 댓글 DTO 생성
> 기타 사항

[#66] ✨feat: 자유게시판 댓글 DTO 생성

---

src/main/java/team/seventhmile/tripforp/domain/review_post/service/ReviewPostService.java
src/test/java/team/seventhmile/tripforp/domain/review_post/service/ReviewPostServiceTest.java

> 리뷰 게시글 서비스, 서비스 테스트 코드 작성
- close #53 
> 주요 변경 사항 목록
>

[#53] ✨ feat: 리뷰 게시글 서비스, 서비스 테스트 코드 구현

---

src/main/java/team/seventhmile/tripforp/domain/plan/controller/PlanLikeController.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/PlanLikeRequestDto.java
src/test/java/team/seventhmile/tripforp/domain/plan/controller/PlanLikeControllerTest.java
src/test/java/team/seventhmile/tripforp/domain/plan/repository/PlanLikeRepositoryTest.java
src/test/java/team/seventhmile/tripforp/domain/plan/service/PlanLikeServiceTest.java

> 여행 코스 좋아요 테스트 코드 작성
- close #58 
> PlanLikeDto 추가
> PlanLikeController 수정
> 컨트롤러, 레포지토리, 서비스 테스트코드 작성
> 기타 사항

[#58] ✨ feat: 여행 코스 좋아요 테스트 코드 작성

---

src/main/java/team/seventhmile/tripforp/domain/free_comment/dto/FreeCommentDto.java
src/main/java/team/seventhmile/tripforp/domain/free_comment/entity/FreeComment.java
src/main/java/team/seventhmile/tripforp/domain/free_comment/repository/FreeCommentRepository.java

> 자유게시판 레포지토리 생성 및 패키지 위치 조정
- close #69 
> 자유게시판 레포지토리 생성 및 패키지 위치 조정
> 기타 사항

[#69] ✨feat: 자유게시판 레포지토리 생성 및 패키지 위치 조정

---

src/main/java/team/seventhmile/tripforp/domain/review_post/service/ReviewPostService.java

updateReviewPost 메서드 plan 추가 구현
- close #82 
> 주요 변경 사항 목록
> 기타 사항

[#82] :sparkles: feat: ReviewPostService updateReviewPost plan 구현

---

src/main/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepositoryCustom.java
src/main/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepositoryImpl.java

커밋 실수로 되돌리는 과정에서 날아간 검색기능 구현하였습니다
- close #84 
> 주요 변경 사항 목록
> 기타 사항

[#84] :sparkles: feat: 리뷰 게시글 검색기능 구현(깃 되돌리기 중 날아감)

---

src/main/java/team/seventhmile/tripforp/domain/free_comment/service/FreeCommentService.java
src/main/java/team/seventhmile/tripforp/domain/magazine/entity/Magazine.java

- 자유게시판 댓글 서비스 구현
- close #80 
- 자유 게시판 댓글 조회
- 자유 게시판 댓글 작성
- 자유 게시판 댓글 수정
- 자유 게시판 댓글 삭제
- Entity -> Dto 변환 메소드
- Dto -> Entity 변환 메소드
- 매거진 게시글 id에 db column 이름 추가 ("magazine_post_id")

[#80] ✨feat: 자유게시판 댓글 서비스 구현

---

src/main/java/team/seventhmile/tripforp/domain/plan/entity/Plan.java

> Plan BaseEntity 적용
- close #76 
> 주요 변경 사항 목록
> 기타 사항

[#76] :sparkles: feat: Plan BaseEntity 적용

---

src/main/java/team/seventhmile/tripforp/global/exception/ErrorResponse.java
src/main/java/team/seventhmile/tripforp/global/exception/GlobalExceptionHandler.java
src/main/java/team/seventhmile/tripforp/global/exception/ResourceNotFoundException.java

> 예외처리 핸들러 구현
- close #90 
유효성 체크와 리소스 존재 체크 예외처리만 구현하였습니다.
추후에 추가 작성이 필요합니다.
> 기타 사항

[#90] :sparkles: feat: 예외처리 핸들러 구현

---

src/main/java/team/seventhmile/tripforp/domain/plan/controller/PlanController.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/CreatePlaceRequest.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/CreatePlanItemRequest.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/CreatePlanRequest.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/UpdatePlanItemRequest.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/UpdatePlanRequest.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/UpdatePlanResponse.java
src/main/java/team/seventhmile/tripforp/domain/plan/entity/Plan.java
src/main/java/team/seventhmile/tripforp/domain/plan/entity/PlanItem.java
src/main/java/team/seventhmile/tripforp/domain/plan/repository/PlanItemRepository.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlaceService.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanItemService.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanService.java
src/main/java/team/seventhmile/tripforp/global/exception/GlobalExceptionHandler.java
src/test/java/team/seventhmile/tripforp/domain/plan/service/PlanServiceTest.java

> 여행 코스 수정, 삭제 구현
- close #88 
> 주요 변경 사항 목록
> 기타 사항

[#88] ✨ feat: 여행 코스 수정, 삭제 구현

---

src/main/java/team/seventhmile/tripforp/domain/plan/dto/PlaceGetDto.java
src/main/java/team/seventhmile/tripforp/domain/plan/entity/Place.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanGetDetailService.java

- close #106 
> 주요 변경 사항 목록
> 기타 사항

[#106] :bug: feat: 오류수정

---

src/test/java/team/seventhmile/tripforp/domain/plan/controller/PlanGetDetailControllerTest.java

- close #109 
> 주요 변경 사항 목록
> 기타 사항

Feat/#109 오류 및 버그 수정

---

src/main/java/team/seventhmile/tripforp/domain/plan/controller/PlanLikeController.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/PlanLikeResponseDto.java
src/main/java/team/seventhmile/tripforp/domain/plan/entity/PlanLike.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanLikeService.java
src/test/java/team/seventhmile/tripforp/domain/plan/controller/PlanLikeControllerTest.java
src/test/java/team/seventhmile/tripforp/domain/plan/service/PlanLikeServiceTest.java

> PlanLikeController 직접반환 엔티티 Dto로 변환
- close #78 
> PlanLikeController 직접반환 엔티티 Dto로 변환
> 변환하면서 생긴 테스트코드에 생긴 버그 수정
> PlanLike 좋아요 생성시간코드 제거
> 기타 사항

[#78] ✨ feat: PlanLikeController 직접반환 엔티티 Dto 변환

---

src/test/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepositoryTest.java
src/test/java/team/seventhmile/tripforp/domain/review_post/service/ReviewPostServiceTest.java

refactor: RepositoryTest LocalDateTime -> LocalDate 수정
- close #85 
> 주요 변경 사항 목록
> 기타 사항
Plan 엔티티 Builder 코드 변경에 따라 ServiceTest 파라미터도 변경되었습니다.

[#85] ✨ refactor: RepositoryTest LocalDateTime -> LocalDate 수정

---

src/main/java/team/seventhmile/tripforp/domain/magazine/entity/Magazine.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/dto/ReviewCommentDto.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/entity/ReviewComment.java

- 리뷰게시판 댓글 엔티티, DTO 생성 
- 자유게시판 댓글, 매거진 엔티티 BaseEntity 적용
- close #95 
- 리뷰게시판 댓글 엔티티, DTO 생성 
- 자유게시판 댓글, 매거진 엔티티 BaseEntity 적용
> 기타 사항

[#95] ✨feat: 리뷰게시판 댓글 엔티티, DTO 생성 / 자유게시판 댓글, 매거진 엔티티 BaseEntity 적용

---

src/main/java/team/seventhmile/tripforp/domain/magazine/entity/Magazine.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/dto/ReviewCommentDto.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/entity/ReviewComment.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/repository/ReviewCommentRepository.java

> 리뷰게시판 댓글 레포지토리 생성
- close #98 
> 리뷰게시판 댓글 레포지토리 생성
> 기타 사항

[#98] ✨feat: 리뷰게시판 댓글 레포지토리 생성

---

src/main/java/team/seventhmile/tripforp/domain/magazine/entity/Magazine.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/dto/ReviewCommentDto.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/entity/ReviewComment.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/repository/ReviewCommentRepository.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/service/ReviewCommentService.java

> 리뷰게시판 댓글 서비스 구현
- close #100 
- 리뷰 게시판 댓글 조회
- 리뷰 게시판 댓글 작성
- 리뷰 게시판 댓글 수정
- 리뷰 게시판 댓글 삭제
- Entity -> Dto 변환 메소드
- Dto -> Entity 변환 메소드
> 기타 사항

[#100] ✨feat: 리뷰게시판 댓글 서비스 구현

---

src/main/java/team/seventhmile/tripforp/domain/magazine/entity/Magazine.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/controller/ReviewCommentController.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/dto/ReviewCommentDto.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/entity/ReviewComment.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/repository/ReviewCommentRepository.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/service/ReviewCommentService.java
src/main/java/team/seventhmile/tripforp/domain/review_post/service/ReviewPostService.java

> 리뷰게시판 댓글 컨트롤러 구현 / 리뷰게시글 서비스 코드 추가
- close #102 
- 댓글 조회
- 댓글 작성 (security 미적용으로 주석처리)
- 댓글 수정 (security 미적용으로 주석처리)
- 댓글 삭제 (security 미적용으로 주석처리)
- ReviewPostService에 ReviewPost엔티티 조회 메소드 추가 (getReviewPostEntity)
- 댓글 작성, 수정, 삭제는 Security 아직 미적용으로, 주석처리

[#102] ✨feat: 리뷰게시판 댓글 컨트롤러 구현 / 리뷰게시글 서비스 코드 추가

---

src/main/java/team/seventhmile/tripforp/domain/review_post/controller/ReviewPostController.java
src/test/java/team/seventhmile/tripforp/domain/review_post/controller/ReviewPostControllerTest.java
src/test/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepositoryTest.java
src/test/java/team/seventhmile/tripforp/domain/review_post/service/ReviewPostServiceTest.java

리뷰게시판 컨트롤러 구현
- close #94 
> 주요 변경 사항 목록
컨트롤러, 테스트 구현
> 기타 사항
시간이 없는 관계로 
ReviewPostServiceTest의 테스트 데이터 파라미터 변경
ReviewPostRepositoryTest의 LocalDateTime -> LocalDate 변경 사항도 함께 커밋하였습니다.

[#94] :sparkles: feature: 리뷰게시판 컨트롤러 구현

---

src/main/java/team/seventhmile/tripforp/domain/free_comment/service/FreeCommentService.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/service/ReviewCommentService.java

> 댓글 서비스 Transactional 추가
- close #112 
- 자유게시판 댓글 서비스
- 리뷰게시판 댓글 서비스
> 기타 사항

[#112] ✨doc: 댓글 서비스 Transactional 추가

---

src/main/java/team/seventhmile/tripforp/domain/free_post/controller/FreePostController.java
src/main/java/team/seventhmile/tripforp/domain/free_post/dto/FreePostDto.java
src/main/java/team/seventhmile/tripforp/domain/free_post/entity/FreePost.java
src/main/java/team/seventhmile/tripforp/domain/free_post/repository/FreePostRepository.java
src/main/java/team/seventhmile/tripforp/domain/free_post/repository/FreePostRepositoryCustom.java
src/main/java/team/seventhmile/tripforp/domain/free_post/repository/FreePostRepositoryImpl.java
src/main/java/team/seventhmile/tripforp/domain/free_post/service/FreePostService.java
src/test/java/team/seventhmile/tripforp/domain/free_post/controller/FreePostControllerTest.java
src/test/java/team/seventhmile/tripforp/domain/free_post/repository/FreePostRepositoryTest.java
src/test/java/team/seventhmile/tripforp/domain/free_post/service/FreePostServiceTest.java

feature: 자유 게시글 컨트롤러, 서비스, 리포지토리 (테스트 포함) 구현
- close #110 
> 주요 변경 사항 목록
자유 게시글 컨트롤러, 서비스, 리포지토리 (테스트 포함) 구현하였습니다.
> 기타 사항

[#110] :sparkles: feature: 자유 게시글 컨트롤러, 서비스, 리포지토리 (테스트 포함) 구현

---

src/main/java/team/seventhmile/tripforp/domain/plan/controller/PlanLikeController.java
src/main/java/team/seventhmile/tripforp/domain/plan/repository/PlanLikeRepository.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanLikeService.java

> 좋아요 높은 순으로 여행코스 5개 조회
- close #97 
> 좋아요 높은 순으로 여행코스 5개 조회
> 기타 사항

[#97] ✨ Feat: 좋아요 기준으로 여행코스 조회

---

src/main/java/team/seventhmile/tripforp/domain/free_post/service/FreePostService.java
src/main/java/team/seventhmile/tripforp/domain/review_post/service/ReviewPostService.java
src/test/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepositoryTest.java
src/test/java/team/seventhmile/tripforp/domain/review_post/service/ReviewPostServiceTest.java

FreePost 컴파일 에러
- close #122 
> 주요 변경 사항 목록
일부 테스트 코드 수정 필요

[#122] 🐛 fix: FreePost 컴파일 에러

---

frontend/src/App.vue
frontend/src/router/index.js
frontend/src/views/FooterView.vue
frontend/src/views/FreePostListView.vue
frontend/src/views/HeaderView.vue
frontend/src/views/LayoutView.vue
frontend/src/views/LoginView.vue
frontend/src/views/PlanDetailView.vue
frontend/src/views/SignupView.vue
frontend/src/views/WritePlanView.vue

- close #124 
> 주요 변경 사항 목록
`cd frontend`
`npm install`
`npm run dev`
http://localhost:3000/

[#124] :sparkles: feat: css 작업 환경 세팅

---

src/main/java/team/seventhmile/tripforp/domain/plan/dto/PlanGetDetailDto.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/PlanGetDto.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanService.java
src/test/java/team/seventhmile/tripforp/domain/plan/controller/PlanControllerTest.java
src/test/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepositoryTest.java

- close #117 
> 주요 변경 사항 목록
> 기타 사항

[#117] :bug: feat: 오류수정

---

src/main/java/team/seventhmile/tripforp/external/alan/service/AlanApiService.java

- close #130 
> 주요 변경 사항 목록
> 기타 사항

[#130] :bug: fix: alan api url 명시

---

Dockerfile
frontend/Dockerfile

> FE, BE DockerFile 작성
- close #77 
> DockerFile 추가
> 기타 사항

[#77] 👷 CI: DockerFile 작성

---

build.gradle
src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
src/main/java/team/seventhmile/tripforp/domain/user/dto/UserDto.java
src/main/java/team/seventhmile/tripforp/domain/user/repository/UserRepository.java
src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java
src/main/java/team/seventhmile/tripforp/global/config/SecurityConfig.java
src/main/java/team/seventhmile/tripforp/global/config/WebConfig.java
src/main/java/team/seventhmile/tripforp/global/exception/user/AlreadyUsedEmailException.java
src/main/java/team/seventhmile/tripforp/global/exception/user/UserExceptionHandler.java
src/main/java/team/seventhmile/tripforp/global/exception/user/UserRegistrationException.java
src/main/java/team/seventhmile/tripforp/global/exception/user/WithdrawnUserException.java
src/test/java/team/seventhmile/tripforp/domain/user/controller/UserControllerTest.java
src/test/java/team/seventhmile/tripforp/domain/user/repository/UserRepositoryTest.java
src/test/java/team/seventhmile/tripforp/domain/user/service/UserServiceTest.java

> 스프링 시큐리티 회원가입 구현
- close #104 
> - build.gradle에 Spring Security dependencies 추가
> - 회원 가입 1차 구현
> - SecurityConfig 설정
> - Exception 핸들링
> - 테스트코드 작성
> 현재 모든 접근에 대해 permitAll 상태입니다.
> 추후 접근 권한 설정 변경 사항이 생길 시 말씀드리도록 하겠습니다.

[#104] ✨ feat: 스프링 시큐리티 회원가입 구현

---

frontend/src/views/FreePostListView.vue

> 자유게시판 목록 화면구현 (데이터 받아오기)
- close #128 
> 자유게시판 목록 화면구현
> 기타 사항

[#128] ✨ feat: 자유게시판 목록 화면구현

---

src/main/java/team/seventhmile/tripforp/domain/free_post/service/FreePostService.java

> 자유게시판 서비스 수정
- close #134 
> FreePost 엔티티 조회 메소드 추가 (comment 위해서)
> 기타 사항

[#134] ✨doc: 자유게시판 서비스 수정

---

src/main/java/team/seventhmile/tripforp/domain/plan/controller/PlanController.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/GetPlanListResponse.java
src/main/java/team/seventhmile/tripforp/domain/plan/repository/PlanRepositoryCustom.java
src/main/java/team/seventhmile/tripforp/domain/plan/repository/PlanRepositoryImpl.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanService.java

- close #149 
> 주요 변경 사항 목록
> 기타 사항

[#149] :bug: fix: 여행 코스 목록 조회 안되는 오류 수정

---

build.gradle
src/main/java/team/seventhmile/tripforp/domain/user/service/CustomUserDetails.java
src/main/java/team/seventhmile/tripforp/domain/user/service/CustomUserDetailsService.java
src/main/java/team/seventhmile/tripforp/global/config/SecurityConfig.java
src/main/java/team/seventhmile/tripforp/global/jwt/JwtFilter.java
src/main/java/team/seventhmile/tripforp/global/jwt/JwtUtil.java
src/main/java/team/seventhmile/tripforp/global/jwt/LoginFilter.java

> 스프링 시큐리티 로그인 구현 및 jwt 토큰 발급
- close #137 
> 로그인 시 JWT 토큰이 헤더에 담겨져 있습니다.
> 로그인 경로는 `"/api/users/signin"` 입니다.
> `username`이 저희가 받는 `email`이라고 생각해주시면 됩니다.
> 현재 role에 상관없이 permitAll 상태입니다.
> 테스트 코드는 추후 작성 예정입니다.
> 수정 사항이나 질문 사항있으면 코멘트 남겨주시면 감사하겠습니다!

[#137] ✨ feat: 스프링 시큐리티 로그인 구현 및 jwt 토큰 발급

---

frontend/src/api/index.js
frontend/src/components/HeaderComponent.vue
frontend/src/components/SelectPlaceComponent.vue
frontend/src/views/PlanDetailView.vue
src/main/java/team/seventhmile/tripforp/domain/plan/dto/CreatePlaceRequest.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/PlaceDto.java
src/main/java/team/seventhmile/tripforp/domain/plan/entity/Place.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlaceService.java
src/test/java/team/seventhmile/tripforp/domain/plan/controller/PlanControllerTest.java

> 여행 코스 상세 조회 화면 구현
- close #144 
- 헤더 일부 수정
- 여행 코스 상세 조회 화면 구현
- Place 엔티티 x, y 필드 추가
> 기타 사항

[#144] ✨ feat: 여행 코스 상세 조회 화면 구현

---

src/main/java/team/seventhmile/tripforp/domain/free_comment/controller/FreeCommentController.java
src/main/java/team/seventhmile/tripforp/domain/free_post/service/FreePostService.java
src/main/java/team/seventhmile/tripforp/domain/magazine/controller/MagazineController.java
src/main/java/team/seventhmile/tripforp/domain/magazine/dto/MagazineDto.java
src/main/java/team/seventhmile/tripforp/domain/magazine/entity/Magazine.java
src/main/java/team/seventhmile/tripforp/domain/magazine/repository/MagazineRepository.java
src/main/java/team/seventhmile/tripforp/domain/magazine/service/MagazineService.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/controller/ReviewCommentController.java

리뷰 댓글, 자유 댓글 권한확인 활성화
- close #141 
- 컨트롤러: 리뷰 댓글, 자유 댓글 권한확인 활성화
> 기타 사항

[#141] ✨docs: 리뷰 댓글, 자유 댓글 권한확인 활성화

---

src/main/java/team/seventhmile/tripforp/domain/plan/dto/PlanGetDetailDto.java
src/main/java/team/seventhmile/tripforp/domain/plan/repository/PlanLikeRepository.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanService.java

> PlanGetDatailDto 는 likeCount 필드에 Plan에 대한 좋아요 개수를 포함
- close #147 
> 주요 변경 사항 목록
> 기타 사항

[#147] ✨ feat: 여행 코스 상세조회 좋아요 객체에서 좋아요 수로 변경

---

.github/workflows/ci-cd.yml
frontend/src/main.js

> Vue 환경파일 추가
- close #166 
> 주요 변경 사항 목록
> 기타 사항

[#166] 👷 CI: Vue 환경파일 추가

---

src/main/java/team/seventhmile/tripforp/domain/magazine/entity/Magazine.java
src/main/java/team/seventhmile/tripforp/domain/review_post/controller/ReviewPostController.java
src/main/java/team/seventhmile/tripforp/domain/review_post/dto/ReviewPostDto.java
src/main/java/team/seventhmile/tripforp/domain/review_post/entity/ReviewPost.java
src/main/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepository.java
src/main/java/team/seventhmile/tripforp/domain/review_post/service/ReviewPostService.java

> 리뷰 게시판 전체 수정
- close #171 
- 글 작성 시에, Plan 글과 연동 기능 추가
- User 불러오기
- 작성자 뿐만 아니라, 관리자도 글 삭제 권한 추가
- 이미지, 동영상 파일 첨부 기능 추가
> 기타 사항

[#171] ✨feat: 리뷰 게시판 전체 수정

---

frontend/src/api/interceptor.js
frontend/src/components/HeaderComponent.vue
frontend/src/components/SearchPlaceComponent.vue
frontend/src/store/index.js
frontend/src/views/LayoutView.vue
frontend/src/views/PlanDetailView.vue
src/main/java/team/seventhmile/tripforp/domain/plan/controller/PlanController.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/GetPlanListResponse.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/GetPlanResponse.java
src/main/java/team/seventhmile/tripforp/domain/plan/entity/Plan.java
src/main/java/team/seventhmile/tripforp/domain/plan/entity/PlanItem.java
src/main/java/team/seventhmile/tripforp/domain/plan/repository/PlanRepositoryCustom.java
src/main/java/team/seventhmile/tripforp/domain/plan/repository/PlanRepositoryImpl.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanService.java
src/main/java/team/seventhmile/tripforp/global/common/BaseEntity.java

> 여행 코스 조회 시 유저 정보 추가
- close #177 
> 주요 변경 사항 목록
> 기타 사항

[#177] ✨ feat: 여행 코스 조회 시 유저 정보 추가

---

src/main/java/team/seventhmile/tripforp/domain/plan/controller/PlanLikeController.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/PlanLikeRequestDto.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanLikeService.java
src/test/java/team/seventhmile/tripforp/domain/plan/controller/PlanLikeControllerTest.java
src/test/java/team/seventhmile/tripforp/domain/plan/service/PlanLikeServiceTest.java

> PlanLikeRequestDto
User user -> Long userId
수정하면서 바뀐 부분 수정
- close #163 
> 주요 변경 사항 목록
> 기타 사항

[#163] 📝 docs: 여행 코스 좋아요 요청값 user -> userId 수정

---

frontend/src/router/index.js
frontend/src/views/ReviewPostListView.vue

- close #185 
> 주요 변경 사항 목록
> 기타 사항

[#185] :sparkles: feat: 리뷰 게시글 목록 화면 세팅

---

frontend/src/components/SelectDayComponent.vue
frontend/src/router/index.js
src/main/java/team/seventhmile/tripforp/domain/plan/controller/PlanController.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/CreatePlaceRequest.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/CreatePlanItemRequest.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/CreatePlanRequest.java
src/main/java/team/seventhmile/tripforp/domain/plan/entity/Plan.java
src/main/java/team/seventhmile/tripforp/domain/plan/entity/PlanItem.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanService.java
src/main/java/team/seventhmile/tripforp/global/exception/ErrorResponse.java
src/main/java/team/seventhmile/tripforp/global/exception/GlobalExceptionHandler.java
src/main/java/team/seventhmile/tripforp/global/exception/UnauthorizedAccessException.java

- close #187 
> 주요 변경 사항 목록
> 기타 사항

[#187] ✨ feat: PlanController 권한 적용, 여행 코스 등록 유효성 검증

---

src/main/java/team/seventhmile/tripforp/domain/file/entity/File.java
src/main/java/team/seventhmile/tripforp/domain/plan/repository/PlanRepository.java
src/main/java/team/seventhmile/tripforp/domain/review_post/controller/ReviewPostController.java
src/main/java/team/seventhmile/tripforp/domain/review_post/dto/ReviewPostDto.java
src/main/java/team/seventhmile/tripforp/domain/review_post/entity/ReviewFile.java
src/main/java/team/seventhmile/tripforp/domain/review_post/entity/ReviewPost.java
src/main/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepository.java
src/main/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepositoryCustom.java
src/main/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepositoryImpl.java
src/main/java/team/seventhmile/tripforp/domain/review_post/service/ReviewPostService.java

리뷰 게시판 전체 수정
- close #188 
- UserId 불러오지 못하는 오류
- 첨부파일 관련 오류 (ManyToMany 대신에 중간엔티티 사용)
- DTO 오류
- 상세조회 할 때마다, View수 +1 증가 로직 추가
> 기타 사항

[#188] ✨bug: 리뷰 게시판 전체 수정

---

src/main/java/team/seventhmile/tripforp/domain/plan/controller/PlanController.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/CreatePlanRequest.java
src/main/java/team/seventhmile/tripforp/domain/plan/repository/PlanRepositoryCustom.java
src/main/java/team/seventhmile/tripforp/domain/plan/repository/PlanRepositoryImpl.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanService.java

> 나의 여행 코스 목록 조회 구현
- close #195 
> 주요 변경 사항 목록
> 기타 사항

[#195] ✨ feat: 나의 여행 코스 목록 조회 구현

---

.gitignore
frontend/src/components/SelectAreaComponent.vue
frontend/src/views/PlanListView.vue

- close #197
> 주요 변경 사항 목록
> 커밋 메시지 오타입니다 나의 여행 코스 -> 여행 코스

[#197] :sparkles: feat: 여행 코스 목록에서 상세 조회 구현

---

frontend/src/api/index.js
frontend/src/views/SignupView.vue
src/main/java/team/seventhmile/tripforp/domain/user/controller/EmailController.java
src/main/java/team/seventhmile/tripforp/domain/user/dto/EmailCodeResponse.java
src/main/java/team/seventhmile/tripforp/domain/user/service/EmailService.java
src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java
src/main/java/team/seventhmile/tripforp/global/exception/AuthCustomException.java
src/main/java/team/seventhmile/tripforp/global/exception/ErrorCode.java
src/main/java/team/seventhmile/tripforp/global/exception/GlobalExceptionHandler.java

> 기존 회원가입 로직에 이메일 인증 기능 추가 및 예외처리
- close #191 
> 회원가입 시 이메일 인증 추가(BE & FE)
> 회원가입 관련 예외처리 Custom Exception 추가
> 예외처리 정리

[#191] ✨ Feat : 회원가입 이메일 인증 기능 추가

---

src/main/java/team/seventhmile/tripforp/global/config/SecurityConfig.java

> SecurityConfig - LogoutFilter 추가
- close #207  
> SecurityConfig
> - CustomLogoutFilter 추가
> 기타 사항

[#207] 🐛 Fix : LogoutFilter 추가

---

frontend/src/api/index.js
frontend/src/views/SignupView.vue
src/main/java/team/seventhmile/tripforp/domain/user/controller/EmailController.java
src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
src/main/java/team/seventhmile/tripforp/domain/user/dto/ApiResponse.java
src/main/java/team/seventhmile/tripforp/domain/user/service/EmailService.java
src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java
src/main/java/team/seventhmile/tripforp/global/exception/ErrorCode.java

> 회원가입 예외 처리 수정
- close #205 
> 회원 가입 시 중복, 탈퇴, 누락인 경우 예외 처리

[#205] ✨fix: 회원가입 예외처리 수정

---

frontend/src/views/SignupView.vue
src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
src/main/java/team/seventhmile/tripforp/domain/user/entity/User.java

>  회원가입 관련 불필요 코드 수정(UserController, User Entity)
- close #210 
>  UserController @RestController로 수정
>  Users Entity @Setter 삭제
> 기타 사항

[#210] ✨Refactor: 회원가입 불필요 코드 & 주석 수정

---

frontend/src/api/index.js
frontend/src/views/SignupView.vue
src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java
src/main/java/team/seventhmile/tripforp/global/exception/ErrorCode.java

> 회원가입 화면 닉네임 중복 검사 구현
- close #204 
> API
> SignUpVue
> 기타 사항

[#204] ✨Feat: 회원가입(FE) 닉네임 중복 검사 구현

---

src/main/java/team/seventhmile/tripforp/domain/user/controller/MyPageController.java
src/main/java/team/seventhmile/tripforp/domain/user/dto/UserInfoResponse.java
src/main/java/team/seventhmile/tripforp/domain/user/service/MyPageService.java
src/main/java/team/seventhmile/tripforp/global/exception/ErrorCode.java

> 마이페이지 개인정보 조회 BE 구현
- close #215 
> 마이페이지
> ErrorCode 추가
> 추후 개인정보 수정 구현 예정

[#215] ✨Feat: 개인정보조회 BE(마이페이지) 구현

---

src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
src/main/java/team/seventhmile/tripforp/domain/user/dto/ModifyPasswordRequest.java
src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java
src/main/java/team/seventhmile/tripforp/global/exception/ErrorCode.java

> 비밀번호 변경 구현
- close #206 
> access 토큰을 통해 이메일 가져옴
> 해당 유저 비밀번호 변경 구현
> ErrorCode 추가
> 기타 사항

[#206] ✨ Feat : 비밀번호 변경 구현

---

frontend/src/components/HeaderComponent.vue
frontend/src/components/SearchPlaceComponent.vue
frontend/src/components/SelectPlaceComponent.vue
frontend/src/router/index.js
frontend/src/views/PlanDetailView.vue
frontend/src/views/PlanListView.vue
src/main/java/team/seventhmile/tripforp/domain/plan/dto/GetPlanResponse.java
src/main/java/team/seventhmile/tripforp/domain/plan/repository/PlanRepositoryImpl.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanService.java

- close #203 
> 주요 변경 사항 목록
> 기타 사항

[#203] ✨ feat: 여행 코스 목록 조회, 상세 조회 세부 화면 추가

---

frontend/src/views/ReviewPostListView.vue

> 리뷰 게시글 목록 html, css
- close #190 
> 주요 변경 사항 목록
> 기타 사항

[#190] ✨feat: 리뷰 게시글 목록 화면 구현

---

src/main/java/team/seventhmile/tripforp/domain/user/controller/MyPageController.java
src/main/java/team/seventhmile/tripforp/domain/user/service/MyPageService.java

> MyPage 충돌 해결 후 에러 수정
- close #229 
> MyPage 충돌 해결 후 "}" 미기입으로 인한 오류 수정
> 기타 사항

[#229] 🐛 Fix : MyPage 충돌 해결 후 에러 수정

---

frontend/src/views/LoginView.vue
frontend/src/views/SignupView.vue
src/main/java/team/seventhmile/tripforp/domain/plan/dto/CreatePlaceRequest.java
src/main/java/team/seventhmile/tripforp/domain/plan/entity/Plan.java
src/main/java/team/seventhmile/tripforp/domain/plan/entity/PlanItem.java
src/main/java/team/seventhmile/tripforp/domain/plan/entity/PlanLike.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlaceService.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanItemService.java

- close #225 
> 주요 변경 사항 목록
> 기타 사항

[#225] ✨ feat: 회원가입, 로그인 css 수정 및 plan 도메인 코드 일부 수정

---

src/main/java/team/seventhmile/tripforp/domain/file/entity/File.java
src/main/java/team/seventhmile/tripforp/domain/magazine/controller/MagazineController.java
src/main/java/team/seventhmile/tripforp/domain/magazine/dto/MagazineDto.java
src/main/java/team/seventhmile/tripforp/domain/magazine/entity/Magazine.java
src/main/java/team/seventhmile/tripforp/domain/magazine/repository/MagazineRepository.java
src/main/java/team/seventhmile/tripforp/domain/magazine/repository/MagazineRepositoryCustom.java
src/main/java/team/seventhmile/tripforp/domain/magazine/repository/MagazineRepositoryImpl.java
src/main/java/team/seventhmile/tripforp/domain/magazine/service/MagazineService.java

> 매거진 게시판 최종 수정
- close #212 
- Custom exception 적용
- RepositoryImpl 생성
- 리뷰 코드와 동일한 포맷으로 전체 변경
> 기타 사항

[#212] ✨bug: 매거진 게시판 최종 수정

---

src/main/java/team/seventhmile/tripforp/domain/file/entity/File.java
src/main/java/team/seventhmile/tripforp/domain/free_post/controller/FreePostController.java
src/main/java/team/seventhmile/tripforp/domain/free_post/dto/FreePostDto.java
src/main/java/team/seventhmile/tripforp/domain/free_post/entity/FreePost.java
src/main/java/team/seventhmile/tripforp/domain/free_post/service/FreePostService.java
src/main/java/team/seventhmile/tripforp/domain/magazine/controller/MagazineController.java
src/main/java/team/seventhmile/tripforp/domain/magazine/dto/MagazineDto.java
src/main/java/team/seventhmile/tripforp/domain/magazine/entity/Magazine.java
src/main/java/team/seventhmile/tripforp/domain/magazine/repository/MagazineRepository.java
src/main/java/team/seventhmile/tripforp/domain/magazine/repository/MagazineRepositoryCustom.java
src/main/java/team/seventhmile/tripforp/domain/magazine/repository/MagazineRepositoryImpl.java
src/main/java/team/seventhmile/tripforp/domain/magazine/service/MagazineService.java

> 자유 게시판 최종 수정
- close #216 
- 일관성을 위한 코드 통일화
- RequestParam -> Authentication
- 게시글 상세 조회시, 조회 수 증가 로직 추가
- 이에 따른 Test 코드 수정 필요

[#216] ✨bug: 자유 게시판 최종 수정

---

frontend/src/views/FreePostListView.vue

> 자유게시판 목록 html, css 수정
- close #220 
> 주요 변경 사항 목록
> 기타 사항

[#220] 📝docs: 자유게시판 목록 html, css 수정

---

src/main/java/team/seventhmile/tripforp/domain/free_comment/controller/FreeCommentController.java
src/main/java/team/seventhmile/tripforp/domain/free_comment/dto/FreeCommentDto.java
src/main/java/team/seventhmile/tripforp/domain/free_comment/dto/GetFreeCommentDto.java
src/main/java/team/seventhmile/tripforp/domain/free_comment/service/FreeCommentService.java
src/main/java/team/seventhmile/tripforp/domain/free_post/controller/FreePostController.java
src/main/java/team/seventhmile/tripforp/domain/free_post/dto/FreePostDto.java
src/main/java/team/seventhmile/tripforp/domain/free_post/entity/FreePost.java
src/main/java/team/seventhmile/tripforp/domain/free_post/service/FreePostService.java
src/main/java/team/seventhmile/tripforp/domain/plan/controller/PlanController.java
src/main/java/team/seventhmile/tripforp/domain/plan/entity/PlanLike.java
src/main/java/team/seventhmile/tripforp/domain/plan/repository/PlaceRepository.java
src/main/java/team/seventhmile/tripforp/domain/plan/repository/PlanRepositoryCustom.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanService.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/controller/ReviewCommentController.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/dto/GetReviewCommentDto.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/service/ReviewCommentService.java
src/main/java/team/seventhmile/tripforp/domain/review_post/controller/ReviewPostController.java
src/main/java/team/seventhmile/tripforp/domain/review_post/dto/ReviewPostDto.java

- close #242 
> 주요 변경 사항 목록
> 기타 사항

[#242] ✨ refactor: 요구 사항 1차 점검 및 수정

---

.github/workflows/main-ci-cd.yml

메인 브랜치 CI/CD 구축
- close #232 
> Main 브랜치에 Push, Pull Request 할 경우 빌드 및 배포

[#232] :construction_worker: CI/CD: 배포 버전 CI/CD 파이프라인 구축

---

src/main/java/team/seventhmile/tripforp/domain/user/controller/EmailController.java
src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
src/main/java/team/seventhmile/tripforp/domain/user/dto/FindPasswordRequest.java
src/main/java/team/seventhmile/tripforp/domain/user/service/EmailService.java
src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java

>  비밀번호 찾기 시 비밀번호 재설정 로직 구현
- close #231 
>  비밀 번호 찾기 시
> - 해당 사용자가 맞는지 이메일 인증(비밀번호 찾기 용 이메일 전송)
> - 인증 확인 후 비밀번호 재설정 로직
> 기타 사항

[#231] ✨ Feat : 비밀번호 찾기 시 비밀번호 재설정 로직 구현

---

frontend/src/api/index.js
frontend/src/components/UpdateInfo.vue
src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java
src/main/java/team/seventhmile/tripforp/global/config/WebConfig.java

> 마이페이지 - 개인정보수정 API 변경
- close #243 
> 개인정보수정 조회, 수정 API 변경
> CSS 수정
> 기타 사항

[#243] ✨ Fix: 마이페이지 개인정보 조회 및 수정 API 수정

---

src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java

> 회원가입 API 수정
- close #253 
> `register`함수 내부에 `isDuplicatedNickname` 검증 추가
> 기타 사항

[#253] 🐛 Fix : 회원가입 API 수정

---

src/main/java/team/seventhmile/tripforp/domain/plan/controller/PlanLikeController.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/PlanLikeDto.java
src/main/java/team/seventhmile/tripforp/domain/plan/dto/PlanLikeResponseDto.java
src/main/java/team/seventhmile/tripforp/domain/plan/repository/PlanLikeRepository.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanLikeService.java

> 좋아요, 좋아요 취소 통합
id로 id 호출에서 이메일 기반 사용자 조회로 변경
- close #239 
> 주요 변경 사항 목록
> 기타 사항

[#239] ✨feat: 좋아요, 좋아요 취소 통합, 이메일 기반 사용자 조회로 변경

---

frontend/src/api/index.js
frontend/src/router/index.js
frontend/src/store/index.js
frontend/src/views/EditFreePostView.vue
frontend/src/views/FreePostDetailView.vue
frontend/src/views/FreePostListView.vue
frontend/src/views/HomeView.vue
frontend/src/views/WriteFreePostView.vue
src/main/java/team/seventhmile/tripforp/domain/free_comment/controller/FreeCommentController.java
src/main/java/team/seventhmile/tripforp/domain/free_comment/dto/GetFreeCommentDto.java
src/main/java/team/seventhmile/tripforp/domain/free_comment/repository/FreeCommentRepository.java
src/main/java/team/seventhmile/tripforp/domain/free_comment/service/FreeCommentService.java
src/main/java/team/seventhmile/tripforp/domain/free_post/dto/FreePostDto.java
src/main/java/team/seventhmile/tripforp/domain/free_post/repository/FreePostRepositoryImpl.java
src/main/java/team/seventhmile/tripforp/domain/user/service/CustomUserDetails.java
src/main/java/team/seventhmile/tripforp/global/jwt/JwtUtil.java
src/main/java/team/seventhmile/tripforp/global/jwt/LoginFilter.java

- close #265 
> 주요 변경 사항 목록
> 기타 사항

[#265] ✨ feat: 자유게시판 상세조회 + 댓글 구현

---

frontend/src/api/index.js
frontend/src/router/index.js
frontend/src/views/LayoutView.vue
frontend/src/views/LoginView.vue
frontend/src/views/ResetPasswordView.vue
src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java

> 비밀번호 재설정 화면 구현 및 API 연결
- close #267 
> router/index, api/index, LayoutView, LoginView, UserController, UserService 
> 기타 사항

[#267] :sparkles: Feat: 비밀번호 재설정 화면 구현 및 API 연결

---

src/main/java/team/seventhmile/tripforp/domain/user/service/EmailService.java

> EmailService 중복 코드 리팩토링
- close #271 
> 인증 이메일 발송 시 중복되는 인증코드 생성 및 발송 코드를 메서드화 했습니다.
> - `emailGenerateAndSend`
> 기타 사항

[#271] ♻️ Refactor : EmailService 중복 코드 리팩토링

---

frontend/src/api/index.js
frontend/src/components/HeaderComponent.vue
frontend/src/components/ItineraryComponent.vue
frontend/src/components/SelectPlaceComponent.vue
frontend/src/router/index.js
frontend/src/store/index.js
frontend/src/views/AdminView.vue
frontend/src/views/EditMagazineView.vue
frontend/src/views/HomeView.vue
frontend/src/views/LayoutView.vue
frontend/src/views/MagazineDetailView.vue
frontend/src/views/PlanDetailView.vue
frontend/src/views/WriteMagazineView.vue
frontend/src/views/WritePlanView.vue
src/main/java/team/seventhmile/tripforp/domain/magazine/controller/MagazineController.java

- close #276 
> 주요 변경 사항 목록
> 기타 사항

[#276] ✨ feat: 관리자 페이지 구현(매거진)

---

frontend/src/api/index.js
frontend/src/components/MyFreePosts.vue
frontend/src/components/MyReviewPosts.vue
frontend/src/views/MypageView.vue
src/main/java/team/seventhmile/tripforp/domain/free_post/repository/FreePostRepository.java
src/main/java/team/seventhmile/tripforp/domain/free_post/service/FreePostService.java

> 마이페이지 내가 작성한 자유/리뷰게시글 목록 조회
- close #274 
> index.js
> MypageView.vue
> 기타 사항

[#274] :sparkles: Feat: 마이페이지 작성한 글 목록 조회 화면 구현

---

frontend/src/api/index.js
frontend/src/router/index.js
frontend/src/views/EditFreePostView.vue
frontend/src/views/EditMagazineView.vue
frontend/src/views/EditReviewPostView.vue
frontend/src/views/FreePostListView.vue
frontend/src/views/MagazineDetailView.vue
frontend/src/views/ReviewPostDetailView.vue
frontend/src/views/ReviewPostListView.vue
frontend/src/views/WriteMagazineView.vue
frontend/src/views/WriteReviewPostView.vue
src/main/java/team/seventhmile/tripforp/domain/free_comment/service/FreeCommentService.java
src/main/java/team/seventhmile/tripforp/domain/free_post/repository/FreePostRepositoryImpl.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/controller/ReviewCommentController.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/dto/GetReviewCommentDto.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/repository/ReviewCommentRepository.java
src/main/java/team/seventhmile/tripforp/domain/review_comment/service/ReviewCommentService.java
src/main/java/team/seventhmile/tripforp/domain/review_post/dto/ReviewPostDto.java
src/main/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepositoryImpl.java
src/main/java/team/seventhmile/tripforp/domain/user/service/EmailService.java

- close #279 
> 주요 변경 사항 목록
> 기타 사항

[#279] :sparkles: feat: 게시판, 매거진 구현

---

src/main/java/team/seventhmile/tripforp/domain/user/service/CustomUserDetailsService.java

> 탈퇴한 사용자가 로그인 되는 문제 해결
- close #285 
> `CustomUserDetailsService` 변경
> 기타 사항

[#271] 🐛 Fix : 탈퇴한 사용자가 로그인 되는 문제 해결

---

src/main/java/team/seventhmile/tripforp/external/alan/controller/AlanApiController.java
src/main/java/team/seventhmile/tripforp/external/alan/dto/AreaRecsRequest.java
src/main/java/team/seventhmile/tripforp/external/alan/service/AlanApiService.java

- close #291
> 주요 변경 사항 목록
> 기타 사항

[#291] :bug: bug: ai 여행 지역 기반의 특별한 여행지추천 수정

---

src/main/java/team/seventhmile/tripforp/domain/user/controller/EmailController.java
src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
src/main/java/team/seventhmile/tripforp/domain/user/dto/EmailCodeRequest.java
src/main/java/team/seventhmile/tripforp/domain/user/dto/FindPasswordRequest.java
src/main/java/team/seventhmile/tripforp/domain/user/dto/ModifyPasswordRequest.java
src/main/java/team/seventhmile/tripforp/domain/user/dto/UserDto.java
src/main/java/team/seventhmile/tripforp/domain/user/dto/UserInfoRequest.java

- close 
> user > dto : validation 적용
> - `EmailCodeRequest`
> - `FindPasswordRequest`
> - `ModifyPasswordRequest`
> - `UserDto`
> - `UserInfoRequest`
> user > cotntroller : `@Valid` 추가
> - `EmailController`
> - `UserController`
> 기타 사항

[#290] ✨ Feat : user validation 추가

---

src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanItemService.java
src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanService.java

> 여행 코스 수정 로직 수정
- close #300 
> 주요 변경 사항 목록
> 기타 사항

[#300] :bug: fix: 여행 코스 수정 로직 수정

---

build.gradle
frontend/src/components/UpdateInfo.vue
src/main/java/team/seventhmile/tripforp/domain/user/dto/UserInfoRequest.java
src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java

> 개인정보 수정 로직 변경
- close #308 
> UpdateInfo, UserService
> 기타 사항

[#308] :necktie: 개인정보수정 로직 변경

---

README.md

- close 
> 주요 변경 사항 목록
> 기타 사항

:memo: 리드미 배포 URL 취소선

---

build.gradle
src/main/java/team/seventhmile/tripforp/domain/course/dto/GetCourseListResponse.java
src/main/java/team/seventhmile/tripforp/domain/course/repository/CourseRepositoryImpl.java
src/main/java/team/seventhmile/tripforp/domain/region/entity/Region.java
src/main/java/team/seventhmile/tripforp/domain/region/service/RegionService.java
src/main/java/team/seventhmile/tripforp/global/config/CacheConfig.java

- close #320 
> 주요 변경 사항 목록
> 기타 사항

[Feat] 코스 목록 조회 API 성능 최적화

---

frontend/Dockerfile
src/main/java/team/seventhmile/tripforp/domain/course/repository/CourseRepositoryImpl.java
src/main/java/team/seventhmile/tripforp/domain/place/dto/GetPlaceCountResponse.java
src/main/java/team/seventhmile/tripforp/domain/spot/repository/SpotRepositoryImpl.java
src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
src/main/java/team/seventhmile/tripforp/domain/user/service/MemoryEmailService.java
src/main/java/team/seventhmile/tripforp/domain/user/service/MemoryUserService.java
src/main/java/team/seventhmile/tripforp/domain/user/service/RedisUserService.java
src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java
src/main/java/team/seventhmile/tripforp/external/google/service/GoogleMapsService.java
src/main/java/team/seventhmile/tripforp/global/config/CacheConfig.java

- close #324 
> 주요 변경 사항 목록
> 기타 사항

[Feat] 성능 최적화

---

frontend/src/api/course.js
frontend/src/components/HeaderComponent.vue
frontend/src/components/course/SelectPlaceComponent.vue
frontend/src/router/index.js
frontend/src/store/index.js
frontend/src/views/HomeView.vue
frontend/src/views/LayoutView.vue
frontend/src/views/course/CourseListView.vue
src/main/java/team/seventhmile/tripforp/domain/magazine/service/MagazineService.java
src/main/java/team/seventhmile/tripforp/domain/region/controller/RegionController.java
src/main/java/team/seventhmile/tripforp/domain/region/dto/GetPopularRegionsResponse.java
src/main/java/team/seventhmile/tripforp/domain/region/repository/RegionRepository.java
src/main/java/team/seventhmile/tripforp/domain/region/repository/RegionRepositoryCustom.java
src/main/java/team/seventhmile/tripforp/domain/region/repository/RegionRepositoryImpl.java
src/main/java/team/seventhmile/tripforp/domain/region/service/RegionService.java
src/main/java/team/seventhmile/tripforp/external/google/controller/GoogleMapsController.java
src/main/java/team/seventhmile/tripforp/global/config/CacheConfig.java

- close #328 
> 주요 변경 사항 목록
> 기타 사항

[Feat] 인기 지역 API 구현

---

.gitignore
frontend/src/api/interceptor.js
frontend/src/components/course/LikedPlans.vue
frontend/src/components/course/MyCourses.vue
frontend/src/components/course/PopularPlacesSideBar.vue
frontend/src/components/course/SidebarToggleButton.vue
frontend/src/components/free/MyFreeComments.vue
frontend/src/components/free/MyFreePosts.vue
frontend/src/components/review/MyReviewComments.vue
frontend/src/components/review/MyReviewPosts.vue
frontend/src/components/user/DeleteAccount.vue
frontend/src/components/user/UpdateInfo.vue
frontend/src/router/index.js
frontend/src/store/index.js
frontend/src/views/LayoutView.vue
frontend/src/views/review/WriteReviewPostView.vue
frontend/src/views/user/LoginView.vue
frontend/src/views/user/MypageView.vue
frontend/src/views/user/ResetPasswordView.vue
src/main/java/team/seventhmile/tripforp/global/jwt/JwtUtil.java
src/main/java/team/seventhmile/tripforp/global/jwt/LoginFilter.java

- close #332 
> 주요 변경 사항 목록
> 기타 사항

[Feat] 마이페이지 ui 수정 및 모바일 적용

---

frontend/src/api/interceptor.js
frontend/src/api/user.js
frontend/src/components/HeaderComponent.vue
frontend/src/components/course/LikedPlans.vue
frontend/src/components/user/UpdateInfo.vue
frontend/src/router/index.js
frontend/src/store/index.js
frontend/src/views/AdminView.vue
frontend/src/views/LayoutView.vue
frontend/src/views/course/CourseDetailView.vue
frontend/src/views/free/EditFreePostView.vue
frontend/src/views/free/FreePostDetailView.vue
frontend/src/views/free/FreePostListView.vue
frontend/src/views/free/WriteFreePostView.vue
frontend/src/views/magazine/EditMagazineView.vue
frontend/src/views/magazine/MagazineDetailView.vue
frontend/src/views/magazine/WriteMagazineView.vue
frontend/src/views/review/EditReviewPostView.vue
frontend/src/views/review/ReviewPostDetailView.vue
frontend/src/views/review/ReviewPostListView.vue
frontend/src/views/review/WriteReviewPostView.vue
src/main/java/team/seventhmile/tripforp/global/config/CacheConfig.java
src/main/java/team/seventhmile/tripforp/global/jwt/CustomLogoutFilter.java
src/main/java/team/seventhmile/tripforp/global/jwt/JwtUtil.java
src/main/java/team/seventhmile/tripforp/global/jwt/LoginFilter.java

- close #336 
> 주요 변경 사항 목록
> 기타 사항

[Feat] 게시판 ui 개선

---

frontend/src/api/course.js
frontend/src/api/gemini.js
frontend/src/components/course/GoogleMapComponent.vue
frontend/src/components/course/ItineraryComponent.vue
frontend/src/components/course/SearchPlaceComponent.vue
src/main/java/team/seventhmile/tripforp/domain/course/controller/CourseController.java
src/main/java/team/seventhmile/tripforp/domain/course/dto/OptimizeRouteRequest.java
src/main/java/team/seventhmile/tripforp/domain/course/dto/RouteResult.java
src/main/java/team/seventhmile/tripforp/domain/course/service/CourseService.java

- close #345 
> 주요 변경 사항 목록
> 기타 사항

[Feat] 동선 최적화 기능 수정 #345

---

frontend/Dockerfile

- close 
> 주요 변경 사항 목록
> 기타 사항

build: vue 도커 파일 수정

---

src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java

- close 
> 주요 변경 사항 목록
> 기타 사항

fix: 리프레시 토큰 재발급 API 권한 삭제
